version: '3.8'
services:
  db:
    container_name: postgresql-server
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=blackspring
      - POSTGRES_PASSWORD=blackspring
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local